chore(): add debug logs for adLoaded, adShown, adClicked, adClosed and adEnded
SuperAwesomeLTD/sa-mobile-sdk-ios pull request #154
Opened 2022-02-03 16:55 UTC by natashashafqat

Adding debug logs for:
- adLoaded
- adShown
- adClicked
- adEnded
- adClosed
- adAlreadyLoaded

@gunhansancar:
**Please let me know if my use of logger anywhere isn't right** (my first time doing mobile development 🙂) - the logs are coming through correctly but unsure on if the logger library is being defined correctly, what log level to use, and if they need tags.

Video below showing logs being generated for all of the above, except `adAlreadyLoaded` - we may not need to test this in QA.

https://user-images.githubusercontent.com/48458132/152389448-752693a2-87a6-461f-b71f-2ae199c9f5f6.mov

2022-02-03 17:20 UTC, gunhansancar requested changes
Please also apply the changes for other unmarked changes

2022-02-03 17:20 UTC, gunhansancar commented on Pod/Classes/UI/Common/AdController.swift
> +        logger.success("Event callback: adClosed")
I would suggest we use `logger.info` mostly as I'd consider `success` for a result of an operation. 
Also since we have `placementId` here maybe we should also log that info as well
e.g.
`logger.info("Ad closed for \(placementId) ")

2022-02-03 17:20 UTC, gunhansancar commented on Pod/Classes/UI/Common/AdController.swift
> +        logger.success("Event callback: adShown")
`logger.info("Ad shown for (placementId) ")`

2022-02-03 17:20 UTC, gunhansancar commented on Pod/Classes/UI/Common/AdController.swift
> +        logger.success("Event callback: adLoaded")
This one has already a log on line 140 so I don't thing we need another log here.

2022-02-03 17:20 UTC, gunhansancar commented on Pod/Classes/UI/Common/AdController.swift
> +        logger.success("Event callback: adClicked")
`logger.info("Ad clicked for (placementId) ")

2022-02-03 17:20 UTC, gunhansancar commented on Pod/Classes/Video/VideoAd.swift
> +                logger.success("Event callback: adLoaded")
`logger.success("Ad load successful for \(response.placementId)")`

2022-02-03 17:20 UTC, gunhansancar commented on Pod/Classes/Video/VideoAd.swift
> +            logger.success("Event callback: adAlreadyLoaded")
logger.info("Ad already loaded for (placementId) ")

2022-02-04 09:43 UTC, natashashafqat commented on Pod/Classes/UI/Common/AdController.swift
> +        logger.success("Event callback: adLoaded")
Only reason I added another was for QA purpose, so someone is able to filter all logs by looking for "Event callback:". Maybe I can remove the log on 140 and add the placementId as doing with the others to line 143?

2022-02-04 11:52 UTC, gunhansancar commented on Pod/Classes/UI/Common/AdController.swift
> +        logger.success("Event callback: adLoaded")
Yes, sure. Let's add `placementId` to line 143 then.

2022-02-04 11:53 UTC, natashashafqat commented on Pod/Classes/UI/Common/AdController.swift
> +        logger.success("Event callback: adLoaded")
@gunhansancar perfect, I'd done that in my last commit 🙂

2022-02-04 13:11 UTC, gunhansancar approved these changes

2022-02-04 13:37 UTC, merged