UI tests/aag 3058 interstitial UI tests
SuperAwesomeLTD/sa-mobile-sdk-ios pull request #294
Opened 2023-04-19 16:46 UTC by thomas-james-1986

## JIRA
[[AAG-3058](https://superawesomeltd.atlassian.net/browse/AAG-3058)]

## DESCRIPTION

This PR adds UI tests for the functionality of interstitials:

1) Rendering the ad content
2) The close button configurations
3) The safe ad visibility configurations
4) The bumper page behaviour
5) The parental gate behaviour

Note:

I've added a couple of useful assertions that assert the colour of the screen in different ways, I've extended `Robot` here as the assertions happen in the robots but perhaps they should live somewhere else?

## SCREENSHOTS
n/a

2023-04-19 18:02 UTC, me2k requested changes
Awesome work Tom, really pleased to see this! 
Can you add a test that combines the parent gate and the bumper please.

2023-04-19 18:02 UTC, me2k commented on Example/SuperAwesomeExampleUITests/Stories/InterstitialUITests.swift
> +        }
Can you add a test that combines the parent gate and the bumper please

2023-04-20 00:46 UTC, thomas-james-1986 commented on Example/SuperAwesomeExampleUITests/Stories/InterstitialUITests.swift
> +        }
Added!

2023-04-20 09:16 UTC, gunhansancar submitted a review, later dismissed

2023-04-20 09:31 UTC, me2k approved these changes
Awesome job Tom, thank you for adding that test.

2023-04-20 09:31 UTC, me2k commented on Example/SuperAwesomeExampleUITests/Robots/ParentGateRobot.swift
> +    }
Genius! I was going to mock, but this is way cooler

2023-04-20 10:33 UTC, me2k approved these changes

2023-04-20 10:34 UTC, merged